### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by MuajAmin** [BotSolver/BetterMint#10]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MuajAmin** [comment]
BetterMint sometimes stops working .Then the elo does not work, the chess engine is very powerful even depth 1. Manfist.jon shows error.

**Comment by BotSolver** [comment]
the engine stopping functionality happens either when settings are invalid, or you premove, and elo only works when limit strength is on, and yes, since depth 1 is still around 1200+ elo.
