### ISSUE TITLE
how to solve this bug?

### ISSUE THREAD

**Issue by MuajAmin** [BotSolver/BetterMint#11]
File
D:\BetterMint\BetterMint Public
Error
Could not load css 'css/depthbar.css' for content script.
Could not load manifest.

**Comment by MuajAmin** [comment]
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.

**Comment by MuajAmin** [comment]
Context
html/options.html
Stack Trace
html/options.html:0 (anonymous function)
Nothing to see here, move along.

**Comment by BotSolver** [comment]
not an issue
