### ISSUE TITLE
Hints dissappears

### ISSUE THREAD

**Issue by MuajAmin** [BotSolver/BetterMint#12]
Hints dissappears..even if i don't premove, hints . Everything is fine with bettermint, is this problem can be solved, it will great for us.

**Comment by Altyd** [comment]
> Hints dissappears..even if i don't premove, hints . Everything is fine with bettermint, is this problem can be solved, it will great for us.

Yes I seem to have the same issue, every so often the hints disappear:
Version: 1.15.0 / 1.55.0
sentry.client.5e3dfd8f.js:14 CHESSBOARD VERSION: 1.55.0
sentry.client.5e3dfd8f.js:14 {key: 'web-ui-sound-enabled'}
sentry.client.5e3dfd8f.js:14 {target: 'metamask-contentscript', data: {…}}
sentry.client.5e3dfd8f.js:14 {target: 'metamask-inpage', data: {…}}
sentry.client.5e3dfd8f.js:14 {target: 'metamask-inpage', data: {…}}
play-computer.client.js:49     GET https://dn0qt3r0xannq.cloudfront.net/chess-RXC9HVsKRD/chess-default/prebid-load.js net::ERR_BLOCKED_BY_CLIENT
onWindowLoad @ play-computer.client.js:49
sentryWrapped @ sentry.client.5e3dfd8f.js:14
load (async)
(anonymous) @ sentry.client.5e3dfd8f.js:14
(anonymous) @ sentry.client.5e3dfd8f.js:14
init @ play-computer.client.js:49
initClient @ play-computer.client.js:13
(anonymous) @ play-computer.client.js:13
(anonymous) @ play-computer.client.js:13
sentryWrapped @ sentry.client.5e3dfd8f.js:14
setTimeout (async)
(anonymous) @ sentry.client.5e3dfd8f.js:14
(anonymous) @ play-computer.client.js:13
init_initClients @ play-computer.client.js:13
initWithHooks @ play-computer.client.js:13
initOptions @ play-computer.client.js:13
initWithHooks @ play-computer.client.js:13
initApp @ play-computer.client.js:13
initPlayComputer @ play-computer.client.js:49
9377 @ play-computer.client.js:49
__webpack_require__ @ play-computer.client.js:51
(anonymous) @ play-computer.client.js:51
__webpack_require__.O @ play-computer.client.js:51
(anonymous) @ play-computer.client.js:51
(anonymous) @ play-computer.client.js:51
sentry.client.5e3dfd8f.js:14 {from: '123456789'}
computer:1 Unchecked runtime.lastError: The message port closed before a response was received.
sentry.client.5e3dfd8f.js:14 {key: 'chat-list-loaded'}
sentry.client.5e3dfd8f.js:14 NOTIFICATIONS_FETCHED
sentry.client.5e3dfd8f.js:14 {key: 'web-ui-sound-enabled'}
sentry.client.5e3dfd8f.js:14 On Move {plyDiff: 1, lineDiff: 0, animate: true, move: {…}, linesReordered: false}
6The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
sentry.client.5e3dfd8f.js:14 On Move {plyDiff: 1, lineDiff: 0, animate: true, move: {…}, linesReordered: false}
sentry.client.5e3dfd8f.js:14 On Move {plyDiff: 1, lineDiff: 0, animate: true, move: {…}, linesReordered: false, …}
sentry.client.5e3dfd8f.js:14 On Move {plyDiff: 1, lineDiff: 0, animate: true, move: {…}, linesReordered: false}
sentry.client.5e3dfd8f.js:14 On Move {plyDiff: 1, lineDiff: 0, animate: true, move: {…}, linesReordered: false, …}
sentry.client.5e3dfd8f.js:14 The engine returned the best move "c7c5" but it's not in the top move list.
(anonymous) @ sentry.client.5e3dfd8f.js:14
ProcessMessage @ bettermint.js:543
StockfishEngine.stockfish.onmessage @ bettermint.js:426
sentry.client.5e3dfd8f.js:14 On Move {plyDiff: 1, lineDiff: 0, animate: true, move: {…}, linesReordered: false}animate: truelineDiff: 0linesReordered: falsemove: {move: 606592, epSquare: -1, halfMoves: 1, castlingW: 48, castlingB: 48, …}plyDiff: 1[[Prototype]]: Object
sentry.client.5e3dfd8f.js:14 On Move {plyDiff: 1, lineDiff: 0, animate: true, move: {…}, linesReordered: false}
sentry.client.5e3dfd8f.js:14 On Move {plyDiff: 1, lineDiff: 0, animate: true, move: {…}, linesReordered: false}
sentry.client.5e3dfd8f.js:14 The engine returned the best move "h2h4" but it's not in the top move list.
(anonymous) @ sentry.client.5e3dfd8f.js:14
ProcessMessage @ bettermint.js:543
StockfishEngine.stockfish.onmessage @ bettermint.js:426
sentry.client.5e3dfd8f.js:14     POST https://o90235.ingest.sentry.io/api/198358/envelope/?sentry_key=20162e70eae1422ea8a429a79c3af592&sentry_version=7 net::ERR_BLOCKED_BY_CLIENT
sendReport @ sentry.client.5e3dfd8f.js:14
BaseTransport._flushOutcomes @ sentry.client.5e3dfd8f.js:14
(anonymous) @ sentry.client.5e3dfd8f.js:14
sentry.client.5e3dfd8f.js:14 {from: '123456789'}
computer:1 Unchecked runtime.lastError: The message port closed before a response was received.

**Comment by BotSolver** [comment]
wait for v2 in our discord https://discord.gg/basic
