### ISSUE TITLE
The engine kept missing checkmate

### ISSUE THREAD

**Issue by KickedTheBucket** [BotSolver/BetterMint#13]
**Describe the bug**
When there is a checkmate, the best move is not a checkmate but instead something else. Which may lead to you losing

**To Reproduce**
1. Play game
2. Play until the enemy is close to checkmate
3. See the best move (turn on Automove to see better)

**Expected behavior**
The best move leads to checkmate

**Screenshots**
None

**Smartphone:**
 - Device: Samsung a30s
 - OS: Android 11
 - Browser Kiwi Browser
 - Version 116.0.5845.72

**Additional context**
Maybe this is because the engine is trying to avoid "ending the game", which would make sense since we do not want to be checkmated or drawn but in this case, we are trying to checkmate the enemy

**Comment by BotSolver** [comment]
wait for v2 in our discord https://discord.gg/basic
