### ISSUE TITLE
BetterMint Glitch?

### ISSUE THREAD

**Issue by Zane3418** [BotSolver/BetterMint#2]
Whenever i try to play chess with this it has error on the extensions page the thing says this to: html/options.html:0 (anonymous function) I dont know whats happening but if someone could help me out id greatly appreciate it

**Comment by Zane3418** [comment]
It was also on chrome btw

**Comment by Zane3418** [comment]
i was expecting the arrows to pop up to but they didnt which was weird i was also on a laptop when this happened

**Comment by AmmarTee** [comment]
Any solution to this? so far?

**Comment by BotSolver** [comment]
fixed.

**Comment by BotSolver** [comment]
> i was expecting the arrows to pop up to but they didnt which was weird i was also on a laptop when this happened

fixed

**Comment by BotSolver** [comment]
> Any solution to this? so far?

fixed
