### ISSUE TITLE
"GET /favicon.ico HTTP/1.1" 404 Not Found

### ISSUE THREAD

**Issue by zarkfire** [BotSolver/BetterMint#28]
Everything was working fine until at some time nothing showed up on chess.com. I went on localhost to see what was happennin and i saw this in the console 
![image](https://github.com/user-attachments/assets/3b83dbb4-76ff-4131-97b6-1711471ee665)
Can someone help?

**Comment by zarkfire** [comment]
Honestly i dont think its linked, but generally its not working atm

**Comment by laksh12344** [comment]
> Everything was working fine until at some time nothing showed up on chess.com. I went on localhost to see what was happennin and i saw this in the console ![image](https://private-user-images.githubusercontent.com/148383047/366986685-3b83dbb4-76ff-4131-97b6-1711471ee665.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMTAxNjUsIm5iZiI6MTcyNjMwOTg2NSwicGF0aCI6Ii8xNDgzODMwNDcvMzY2OTg2Njg1LTNiODNkYmI0LTc2ZmYtNDEzMS05N2I2LTE3MTE0NzFlZTY2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNFQxMDMxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NGEwNGQwOTliOWJiNGIzNGE1YmM4ZmI4NDYzYTUwMWMwMjM0YTg1YzVlMzBlNTM5OTk4Y2I2Njg4MDUxNjAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XXbsLUTdopz1qWQwCwVj7hP4ptFzfb3_gELTZUzcFz0) Can someone help?

same issue chessmint and bettermint extensions are not working on chess.com and when we turn the extension on the pop up too is not coming!! whats the issue ?

**Comment by BotSolver** [comment]
already done or this issue doesn't apply to anything of substance.
