### ISSUE TITLE
html/options.html:0 (anonymous functions)

### ISSUE THREAD

**Issue by OSHIBO4930** [BotSolver/BetterMint#29]
Since yesterday, BetterMint has not been working for me and I am writing this text that you will answer me... It all started with the fact that when I went to chess.com and I decided to play with the bot, I found that the arrows on it show, as well as the rest of the BetterMint functions. Then, I went into the extensions and saw an error called html/options.htm . I tried to reinstall the cheat, nothing has changed. Then I tried to install a cheat on my phone, but it's still the same scenario. Kind people, help me, what should I do???

**Comment by admiralwardeath** [comment]
Duplicated issue https://github.com/BotSolver/BetterMint/issues/4

**Comment by BotSolver** [comment]
already done or this issue doesn't apply to anything of substance.
