### ISSUE TITLE
How do I start it up?

### ISSUE THREAD

**Issue by Crosshairs2** [BotSolver/BetterMint#31]
I've gotten it to work, but mostly by reloading chess.com, opening localhost:8000 at random times, and reloading the script if it stops working. What is the main way to open/use BetterMint? Also, the config does not update unless I restart BetterMint. One other thing is that if I start another game, it just stops working until I reload it, which is a pain because I don't really know how.

What is the intended way of opening the bot, is there a way to update the config in-game, and is there a way to not need to reset BetterMint in between games?

Laptop
Windows 11
Chrome
V2 Update Fix Again

**Comment by Aakrithi** [comment]
Same here can you give the complete guide please.. It would help a lot

**Comment by BotSolver** [comment]
already done or this issue doesn't apply to anything of substance.
