### ISSUE TITLE
idk 

### ISSUE THREAD

**Issue by Dream3084** [BotSolver/BetterMint#34]
Task exception was never retrieved future: <Task finished name='Task-9' coro=<websocket_endpoint.<locals>.read_from_socket() done, defined at D:\Download\BetterMint (1)\BetterMint\EngineWS\main.py:100> exception=RuntimeError('WebSocket is not connected. Need to call "accept" first.')> Traceback (most recent call last):   File "D:\Download\BetterMint (1)\BetterMint\EngineWS\main.py", line 101, in read_from_socket     async for data in websocket.iter_text():         print(f"Client: {data}")         stockfish.put(data)   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\websockets.py", line 146, in iter_text     yield await self.receive_text()           ^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\websockets.py", line 117, in receive_text     raise RuntimeError('WebSocket is not connected. Need to call "accept" first.') RuntimeEr

**Comment by BotSolver** [comment]
already done or this issue doesn't apply to anything of substance.
