### ISSUE TITLE
html/options.html:0 (anonymous function)

### ISSUE THREAD

**Issue by KitsuneTheBloodFox** [BotSolver/BetterMint#4]
After adding the extension with no problems and trying to play against a bot, no arrows popped out so of course my reaction was
to go and look into the bug, and it said :
"Uncaught (in promise) Error: This request exceeds the MAX_WRITE_OPERATIONS_PER_MINUTE quota.
Context
html/options.html
Stack Trace
html/options.html:0 (anonymous function)"

idrk how to fix it and if its a problem with MY pc, but MintChes also had a lookalike problem for more people when just me and so
I think it's a problem with the code and chess.com trying to work together.

but my guess is that it's missing the required file loader

**Comment by BotSolver** [comment]
> After adding the extension with no problems and trying to play against a bot, no arrows popped out so of course my reaction was to go and look into the bug, and it said : "Uncaught (in promise) Error: This request exceeds the MAX_WRITE_OPERATIONS_PER_MINUTE quota. Context html/options.html Stack Trace html/options.html:0 (anonymous function)"
> 
> idrk how to fix it and if its a problem with MY pc, but MintChes also had a lookalike problem for more people when just me and so I think it's a problem with the code and chess.com trying to work together.
> 
> but my guess is that it's missing the required file loader

That's just it making a connection with the settings, it's normal.

either settings issue, or just a bad inject, it should work.
