### ISSUE TITLE
Hints dissappears

### ISSUE THREAD

**Issue by ItzShuto** [BotSolver/BetterMint#5]
**Describe the bug**
(In chess.com when i premove or when i try to play fast the the arrow dissappears )and appears only when i restart the website this problem happening to me every brine  itye arrow dissappears every time when i premove or try to play fast pls resolve this bug as soon as possible

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android
 - Browser: kiwi
 - Version : 116.0.5845.26

**Smartphone (please complete the following information):**
 - Device: Resmi note 9 prime
 - OS: Android 11
 - Browser : kiwi
 - Version : 116.0.5845.26

**Additional context**

**Comment by BotSolver** [comment]
We are looking into this, any kind of premove is too much for bettermint at the moment, thank you for the concern and sorry for the late reply, I would avoid premoving at the moment.

**Comment by BotSolver** [comment]
wait for v2 in our discord https://discord.gg/basic
