### ISSUE TITLE
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist. Context html/options.html Stack Trace html/options.html:0 (anonymous function)      

### ISSUE THREAD

**Issue by scramledge** [BotSolver/BetterMint#6]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BotSolver** [comment]
that error does nothing, it's just a error we haven't catched since we didn't see a point to it, you can rest easy.
