### ISSUE TITLE
Pls make it work on Lichess too

### ISSUE THREAD

**Issue by 4Yuri** [BotSolver/BetterMint#7]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 4Yuri** [comment]
It would be nice if in addition to being able to use it on chess.com, you could also use it on lichess

**Comment by BotSolver** [comment]
join the discord and wait

**Comment by 4Yuri** [comment]
"impossible to join it"
