### ISSUE TITLE
Add "Rate possible moves" feature from SakaSperto

### ISSUE THREAD

**Issue by Scharzgrad** [BotSolver/BetterMint#8]
When you click on a piece, that feature should highlight legal squares for it colored to represent the quality of the move - for example, red is a blunder, yellow is a mistake and green is good. It is very bugged in SakaSperto, I hope to see this feature in BetterMint
Edit: It's actually "rate possible moves" feature and not blunder prevention

**Comment by BotSolver** [comment]
we have this planned already for V2.
