### ISSUE TITLE
Multiple line option is broken with NNUE

### ISSUE THREAD

**Issue by YomostXme** [BotSolver/BetterMint#9]
**Describe the bug**
Latest version's multiple line option is broken when I turn on NNUE. Previous versions still work fine.

**To Reproduce**

**Expected behavior**
It should show multiple line on the board

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Window 11
 - Browser: Brave
 - Version: Brave 1.57.57

**Smartphone (please complete the following information):**

 - Device: Redmi note 9 prime
 - OS: Android 11
 - Browser : kiwi
 - Version : 116.0.5845.26

**Additional context**

**Comment by BotSolver** [comment]
yes thats a thing, I'm working on it

**Comment by BotSolver** [comment]
wait for v2 in our discord https://discord.gg/basic
